# Generated by Django 3.1.7 on 2021-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_identifier', models.CharField(max_length=50)),
                ('date_inserted', models.DateTimeField(blank=True, null=True)),
                ('date_transmitted', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, choices=[('Owner', '0'), ('System', 'S')], max_length=10)),
                ('metadata_key', models.TextField(max_length=200)),
                ('metadata_key_hash', models.CharField(max_length=200)),
                ('metadata_hash', models.TextField(max_length=200)),
                ('metadata', models.JSONField(blank=True)),
                ('record_status', models.CharField(blank=True, choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataLedger',
            fields=[
                ('unique_record_identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(blank=True, max_length=255)),
                ('date_inserted', models.DateTimeField(blank=True, null=True)),
                ('metadata_key', models.CharField(max_length=200)),
                ('metadata_key_hash', models.CharField(max_length=200)),
                ('metadata_hash', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True)),
                ('record_status', models.CharField(blank=True, choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('date_validated', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_identifier', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=255)),
                ('date_inserted', models.DateTimeField(blank=True, null=True)),
                ('metadata_key', models.TextField(max_length=200)),
                ('metadata_key_hash', models.CharField(max_length=200)),
                ('metadata_hash', models.TextField(max_length=200)),
                ('metadata', models.JSONField(blank=True)),
                ('record_status', models.CharField(blank=True, choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('date_validated', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='XISConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_schema', models.CharField(default='p2881_schema.json', help_text='Enter the target schema file to validate from.', max_length=200)),
            ],
        ),
    ]
