# Generated by Django 3.1.6 on 2021-02-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XISConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_target_mapping', models.CharField(default='p2881_target_metadata_schema.json', help_text='Enter the schema file to map target.', max_length=200)),
                ('target_metadata_schema', models.CharField(default='p2881_target_validation_schema.json', help_text='Enter the target schema file to validate from.', max_length=200)),
            ],
        ),
    ]
