# Generated by Django 3.1.13 on 2021-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplementalledger',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='supplementalledger',
            name='date_validated',
        ),
        migrations.RemoveField(
            model_name='supplementalledger',
            name='metadata_validation_status',
        ),
        migrations.AlterField(
            model_name='metadataledger',
            name='composite_ledger_transmission_status',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R')], default='Ready', max_length=10),
        ),
        migrations.AlterField(
            model_name='senderemailconfiguration',
            name='sender_email_address',
            field=models.EmailField(help_text='Enter sender email address to send log data from', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplementalledger',
            name='composite_ledger_transmission_status',
            field=models.CharField(blank=True, choices=[('Successful', 'S'), ('Failed', 'F'), ('Pending', 'P'), ('Ready', 'R')], default='Ready', max_length=10),
        ),
    ]
