# Generated by Django 3.2.25 on 2024-03-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20240215_2158'),
        ('core', '0015_alter_xisdownstream_xis_api_key'),
    ]

    operations = [
    ]
