# Generated by Django 3.1.6 on 2021-02-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_identifier', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=255)),
                ('date_inserted', models.DateTimeField(blank=True, null=True)),
                ('metadata_key', models.TextField()),
                ('metadata_hash', models.TextField(max_length=200)),
                ('metadata', models.JSONField(blank=True)),
                ('record_status', models.CharField(blank=True, choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_date', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SupplementalLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_record_identifier', models.CharField(max_length=50)),
                ('agent_name', models.CharField(max_length=255)),
                ('date_inserted', models.DateTimeField(blank=True, null=True)),
                ('metadata_key', models.TextField()),
                ('metadata_hash', models.TextField(max_length=200)),
                ('metadata', models.JSONField(blank=True)),
                ('record_status', models.CharField(blank=True, choices=[('Active', 'A'), ('Inactive', 'I')], max_length=10)),
                ('date_deleted', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_date', models.DateTimeField(blank=True, null=True)),
                ('metadata_validation_status', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10)),
            ],
        ),
    ]
